site_name: Cloud and hyperscale application devops group
site_description: Research and teaching group at University of Rijeka Faculty of Information Technology
site_author: Vedran Miletić
copyright: Copyright 2011 – 2021, Vedran Miletić and collaborators; contents licensed under CC-BY-NC-ND 4.0, except teaching materials at /hr/nastava/ which are licensed under CC-BY-SA 4.0.
repo_url: https://github.com/chadgroup/website/
edit_uri: blob/main/docs/
theme:
  name: material
  features:
    - header.autohide
  language: hr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  alternate:
    - name: Croatian
      link: /hr/
      lang: hr
    - name: English
      link: /en/
      lang: en
